export enum SysCode {
  SUCCESS = '200',
  DATE_FORMAT_ERROR = 'V001',
  DATE_PARSE_ERROR = 'V002',
  DATA_VALIDATION_ERROR = 'V003',
  BAD_REQUEST = 'V400',
  PATH_NOT_FOUND = 'V404',
  UNKNOWN_ERROR = 'V999',

  REDIS_LOCK_FAILED = 'R001',
}
